### ISSUE TITLE
Summary data script doesn't switch to april well 

### ISSUE THREAD

**Issue by mccabete** [EcoForecast/fire_area_forecast#30]
The 02.2_summary_mete.R script doesn't seem to be able to update the summary_data_8days.csv to include april. Specifically [this line](https://github.com/EcoForecast/fire_area_forecast/blob/master/02.2_summary_mete.R#L36) seems to be messing up. 

For example when I run the line like this: 
```
(as.numeric('20190407')-as.numeric('20190306'))
```
it returns
```
[1] 101
```
Instead of a multiple of 8.  This is probably because it is treating the dates as numbers, not calendar dates.   I will look for a solution but @shijuanchen could you check my work?

**Comment by shijuanchen** [comment]
Hi Tess, @mccabete sorry for the late reply. Have you solved the problem yet? If not, I will look into it.

**Comment by mccabete** [comment]
I did.
